-- Dados extraídos de deep-research-report.md; veja README.md antes de publicar.
BEGIN;
INSERT INTO public.specialties (slug, name, program_years, total_training_years, prerequisite, surgical_profile, weekly_hours_min, weekly_hours_max, quality_of_life_potential, telemedicine_potential, work_settings, market_absorption_proxy, future_demand_trend, ai_task_exposure, geographic_market, market_note, career_paths, private_practice_potential, hospital_potential, research_teaching_potential, clinic_class, capital_requirement, private_revenue_potential, economic_note) VALUES
  ('medicina-de-familia-e-comunidade', 'Medicina de Família e Comunidade', 2, 2, NULL, 'Não', 40, 50, 'Média-alta', 'Alta', 'UBS, SUS, clínica, gestão, tele', 'Muito alta', '↑↑', 'Média', 'Brasil inteiro; interior N/NE especialmente', 'alta segurança geográfica', 'cuidados paliativos, preceptoria, gestão, saúde digital', 'Média', 'Média', 'Alta', 'A', 'Baixo', 'Médio', 'pode começar extremamente enxuto'),
  ('clinica-medica', 'Clínica Médica', 2, 2, NULL, 'Não', 44, 60, 'Média', 'Média-alta', 'hospital, ambulatório, plantão, ensino', 'Alta', '↑', 'Média-alta', 'todos os estados', 'porta para muitas áreas; forte plantão', 'pré-requisito para múltiplas áreas', 'Média', 'Muito alta', 'Alta', 'A', 'Baixo', 'Médio', 'forte dependência de volume/rede'),
  ('pediatria', 'Pediatria', 3, 3, NULL, 'Não', 40, 60, 'Média', 'Média', 'hospital, consultório, emergência', 'Alta', '↔/↑', 'Baixa-média', 'todos; grandes capitais + interior', 'população infantil cai, mas oferta assistencial segue desigual', 'neo, cardio ped., pneumo ped., endócrino ped., UTI', 'Alta', 'Alta', 'Alta', 'A–B', 'Baixo', 'Alto', 'fidelização familiar'),
  ('ginecologia-e-obstetricia', 'Ginecologia e Obstetrícia', 3, 3, NULL, 'Parte', 45, 65, 'Baixa-média', 'Média', 'maternidade, consultório, cirurgia', 'Muito alta', '↑', 'Baixa', 'todos; carência interior/NE', 'demanda estável + cirurgia + obstetrícia', 'fetal, reprodução, oncogineco, endoscopia ginecológica', 'Alta', 'Alta', 'Alta', 'B–C', 'Médio', 'Alto', 'ultrassom/procedimentos aumentam CAPEX'),
  ('psiquiatria', 'Psiquiatria', 3, 3, NULL, 'Não', 30, 50, 'Alta', 'Muito alta', 'consultório, CAPS, hospital, tele', 'Muito alta', '↑↑', 'Média', 'grandes cidades e cidades médias', 'excelente telemedicina e particular', 'infância, geriátrica, dependência, forense', 'Muito alta', 'Média', 'Alta', 'A', 'Muito baixo', 'Muito alto', 'excelente margem/tele'),
  ('dermatologia', 'Dermatologia', 3, 3, NULL, 'Parte', 30, 45, 'Alta', 'Alta', 'consultório, procedimentos, hospital', 'Alta', '↑', 'Média-alta', 'capitais: SP/RJ/MG/DF/RS/PR; BA/PE/CE', 'forte privado, maior saturação urbana', 'cirurgia derm., oncologia cutânea, cosmiatria', 'Muito alta', 'Baixa-média', 'Média', 'B–C', 'Médio-alto', 'Muito alto', 'lasers podem elevar investimento drasticamente'),
  ('anestesiologia', 'Anestesiologia', 3, 3, NULL, 'Não; procedural', 40, 60, 'Média', 'Baixa', 'centro cirúrgico, obstetrícia, UTI', 'Muito alta', '↑', 'Baixa', 'polos cirúrgicos; déficit interior', 'remuneração ligada a volume cirúrgico', 'dor, anestesia regional, obstétrica, cardio', 'Baixa', 'Muito alta', 'Média', 'dispensável/A', 'Muito baixo', 'Médio', 'ativo econômico é rede hospitalar, não consultório'),
  ('medicina-de-emergencia', 'Medicina de Emergência', 3, 3, NULL, 'Não; procedural', 36, 60, 'Baixa-média', 'Baixa', 'pronto-socorro, SAMU, gestão', 'Muito alta', '↑', 'Baixa-média', 'universal hospitalar', 'alta empregabilidade, custo de noites', 'toxicologia, trauma, ultrassom point-of-care', 'Baixa', 'Muito alta', 'Média', 'dispensável', 'Muito baixo', 'Baixo', 'carreira predominantemente hospitalar'),
  ('medicina-intensiva', 'Medicina Intensiva', 3, 3, NULL, 'Não; procedural', 36, 60, 'Baixa-média', 'Média', 'UTI, hospital, tele-UTI', 'Muito alta', '↑', 'Baixa-média', 'capitais e hospitais regionais', 'hospital-dependente', 'cardiointensivismo, neurointensivismo', 'Baixa', 'Muito alta', 'Alta', 'dispensável', 'Muito baixo', 'Baixo', 'hospitalar'),
  ('neurologia', 'Neurologia', 3, 3, NULL, 'Não', 40, 55, 'Média', 'Alta', 'hospital, ambulatório, consultório', 'Alta', '↑↑', 'Média', 'capitais e polos regionais', 'envelhecimento favorece demanda', 'vascular, epilepsia, neuroimuno, movimento, cognição', 'Alta', 'Alta', 'Muito alta', 'A–B', 'Baixo-médio', 'Alto', 'EEG/EMG mudam estrutura'),
  ('oftalmologia', 'Oftalmologia', 3, 3, NULL, 'Parte', 35, 50, 'Alta', 'Média', 'consultório, cirurgia, diagnóstico', 'Alta', '↑↑', 'Média-alta', 'capitais/polos regionais', 'envelhecimento + procedimentos', 'retina, córnea, glaucoma, catarata, plástica ocular', 'Muito alta', 'Média', 'Alta', 'C', 'Alto', 'Muito alto', 'diagnósticos/equipamentos criam barreira'),
  ('otorrinolaringologia', 'Otorrinolaringologia', 3, 3, NULL, 'Parte', 35, 50, 'Alta', 'Média', 'consultório, hospital, cirurgia', 'Alta', '↑', 'Média', 'capitais/polos; déficit interior', 'combinação consultório/cirurgia', 'otologia, rinologia, cabeça/pescoço, laringologia', 'Muito alta', 'Alta', 'Alta', 'B–C', 'Médio', 'Muito alto', 'endoscopia/audiologia elevam retorno e CAPEX'),
  ('ortopedia-e-traumatologia', 'Ortopedia e Traumatologia', 3, 3, NULL, 'Sim/parte', 45, 60, 'Média-baixa', 'Baixa', 'hospital, trauma, clínica, cirurgia', 'Muito alta', '↑↑', 'Baixa', 'todos os grandes hospitais', 'envelhecimento + trauma', 'joelho, quadril, coluna, ombro, mão, trauma', 'Muito alta', 'Alta', 'Alta', 'A–B', 'Baixo-médio', 'Muito alto', 'cirurgias usam infraestrutura hospitalar'),
  ('cirurgia-geral', 'Cirurgia Geral', 3, 3, NULL, 'Sim', 50, 65, 'Baixa', 'Baixa', 'hospital, emergência, cirurgia', 'Muito alta', '↑', 'Baixa', 'universal; forte déficit interior', 'grande portabilidade geográfica', 'digestiva, trauma, bariátrica, coloprocto etc.', 'Alta', 'Muito alta', 'Alta', 'A', 'Baixo', 'Alto', 'centro cirúrgico geralmente de terceiros'),
  ('neurocirurgia', 'Neurocirurgia', 5, 5, NULL, 'Sim', 50, 70, 'Baixa', 'Baixa', 'hospital terciário, cirurgia', 'Média-alta', '↑', 'Baixa', 'SP/RJ/MG/RS/PR/DF; Salvador como polo NE', 'mercado concentrado em alta complexidade', 'coluna, vascular, tumor, funcional, pediátrica', 'Alta', 'Muito alta', 'Muito alta', 'A', 'Baixo', 'Alto', 'infraestrutura é hospitalar'),
  ('radiologia-e-diagnostico-por-imagem', 'Radiologia e Diagnóstico por Imagem', 3, 3, NULL, 'Não/parte interv.', 36, 50, 'Alta', 'Muito alta', 'hospital, diagnóstico, teleradiologia', 'Alta', '↑', 'Alta para tarefas', 'capitais + teleradiologia nacional', 'produtividade mudará com IA', 'neuro, tórax, músculo-esquelética, intervenção', 'Alta', 'Muito alta', 'Alta', 'D se própria', 'Muito alto', 'Alto', 'sem clínica própria pode trabalhar remoto/hospital'),
  ('patologia', 'Patologia', 3, 3, NULL, 'Não', 35, 45, 'Alta', 'Alta com digitalização', 'laboratório, hospital, pesquisa', 'Média-alta', '↑', 'Alta para tarefas', 'laboratórios e centros oncológicos', 'digitalização muda fluxo, não elimina responsabilidade', 'hematopatologia, dermato, molecular, citopatologia', 'Baixa', 'Alta', 'Muito alta', 'D se laboratório', 'Muito alto', 'Médio', 'carreira não exige laboratório próprio'),
  ('infectologia', 'Infectologia', 3, 3, NULL, 'Não', 40, 55, 'Média', 'Alta', 'hospital, ambulatório, CCIH, saúde pública', 'Alta', '↑', 'Média', 'hospitais, capitais, vigilância', 'valor em CCIH/AMR/epidemias', 'HIV, transplante, CCIH, tropical, stewardship', 'Média', 'Alta', 'Muito alta', 'A', 'Baixo', 'Médio', 'hospital/CCIH relevante'),
  ('cardiologia', 'Cardiologia', 2, 4, 'clinica_medica', 'Não/parte interv.', 40, 60, 'Média', 'Média-alta', 'hospital, clínica, diagnóstico', 'Muito alta', '↑↑', 'Média-alta', 'universal, forte nos grandes estados', 'envelhecimento e DCV sustentam volume', 'hemodinâmica, eletrofisio, imagem, IC', 'Muito alta', 'Muito alta', 'Alta', 'B–C', 'Médio', 'Muito alto', 'ECG, Holter, MAPA, eco elevam verticalização'),
  ('endocrinologia-e-metabologia', 'Endocrinologia e Metabologia', 2, 4, 'clinica_medica', 'Não', 35, 50, 'Alta', 'Muito alta', 'consultório, ambulatório, tele', 'Alta', '↑↑', 'Média', 'grande mercado ambulatorial', 'diabetes/obesidade + tele', 'diabetes, obesidade, tireoide, hipófise', 'Muito alta', 'Baixa-média', 'Alta', 'A', 'Baixo', 'Muito alto', 'excelente relação capital/consultório'),
  ('gastroenterologia', 'Gastroenterologia', 2, 4, 'clinica_medica', 'Parte endoscópica', 40, 55, 'Média-alta', 'Média', 'clínica, hospital, endoscopia', 'Alta', '↑', 'Baixa-média', 'capitais e cidades médias', 'endoscopia melhora barreira competitiva', 'hepatologia, endoscopia avançada, motilidade', 'Muito alta', 'Alta', 'Alta', 'A ou C/D', 'baixo se consulta; alto se endoscopia', 'Muito alto', 'endoscopia é divisor econômico'),
  ('geriatria', 'Geriatria', 2, 4, 'clinica_medica', 'Não', 35, 50, 'Média-alta', 'Alta', 'clínica, hospital, home care', 'Muito alta', '↑↑', 'Baixa-média', 'ainda subofertada fora dos centros', 'uma das teses demográficas mais fortes', 'paliativos, cognição, fragilidade', 'Alta', 'Alta', 'Alta', 'A', 'Baixo', 'Alto', 'home care é opção adicional'),
  ('hematologia-e-hemoterapia', 'Hematologia e Hemoterapia', 2, 4, 'clinica_medica', 'Não', 40, 55, 'Média', 'Média', 'hospital, hemocentro, oncologia', 'Alta', '↑', 'Média', 'centros terciários/oncológicos', 'forte hospital/pesquisa', 'transplante, hemostasia, hemato-oncologia', 'Média', 'Muito alta', 'Muito alta', 'A', 'Baixo', 'Médio', 'infraestrutura oncológica é institucional'),
  ('nefrologia', 'Nefrologia', 2, 4, 'clinica_medica', 'Não/parte procedural', 40, 60, 'Média-baixa', 'Média', 'hospital, diálise, consultório', 'Muito alta', '↑↑', 'Baixa-média', 'diálise/hospital em todo país', 'doença crônica sustenta demanda', 'transplante, diálise, glomerulopatias', 'Média', 'Muito alta', 'Alta', 'A ou D', 'baixo consultório; enorme diálise', 'Médio', 'clínica de diálise é negócio distinto'),
  ('pneumologia', 'Pneumologia', 2, 4, 'clinica_medica', 'Não/parte procedural', 40, 55, 'Média', 'Alta', 'hospital, consultório, função pulmonar', 'Alta', '↑', 'Média', 'polos regionais', 'crônicas, sono, oncologia, função pulmonar', 'sono, intervenção, função pulmonar, oncologia', 'Alta', 'Alta', 'Alta', 'A–C', 'Médio', 'Alto', 'espirometria/sono agregam receita'),
  ('reumatologia', 'Reumatologia', 2, 4, 'clinica_medica', 'Não', 35, 50, 'Alta', 'Alta', 'consultório, ambulatório, hospital', 'Alta', '↑', 'Média', 'capitais e cidades médias', 'seguimento longitudinal e biológicos', 'doenças sistêmicas, ultrassom, imunobiológicos', 'Muito alta', 'Média', 'Alta', 'A', 'Baixo', 'Muito alto', 'seguimento longitudinal'),
  ('oncologia-clinica', 'Oncologia Clínica', 3, 5, 'clinica_medica', 'Não', 40, 55, 'Média', 'Média-alta', 'centro oncológico, hospital, pesquisa', 'Muito alta', '↑↑', 'Média', 'centros oncológicos; expansão regional', '781 mil casos/ano estimados', 'tumores por sítio, pesquisa clínica, precisão', 'Alta', 'Muito alta', 'Muito alta', 'A', 'Baixo pessoal', 'Alto', 'infusão normalmente institucional'),
  ('urologia', 'Urologia', 3, 6, 'cirurgia_geral', 'Parte/sim', 40, 60, 'Média', 'Média', 'hospital, consultório, cirurgia', 'Alta', '↑↑', 'Baixa', 'polos cirúrgicos', 'envelhecimento masculino + cirurgia', 'uro-onco, robótica, endourologia, andrologia', 'Muito alta', 'Alta', 'Alta', 'B–C', 'Médio', 'Muito alto', 'procedimento/cirurgia amplia receita'),
  ('cirurgia-plastica', 'Cirurgia Plástica', 3, 6, 'cirurgia_geral', 'Sim', 40, 60, 'Média-alta', 'Baixa-média', 'hospital, consultório, cirurgia', 'Média-alta', '↑', 'Baixa', 'muito dependente de renda local no eletivo', 'alto upside e alta competição reputacional', 'estética, mama, crânio-maxilo, queimados, mão', 'Muito alta', 'Alta', 'Média', 'B', 'Médio', 'Muito alto', 'marketing reputacional e particular dominam'),
  ('cirurgia-vascular', 'Cirurgia Vascular', 2, 5, 'cirurgia_geral', 'Sim/parte', 45, 65, 'Média-baixa', 'Baixa-média', 'hospital, clínica vascular, cirurgia', 'Alta', '↑↑', 'Baixa', 'hospitais + centros vasculares', 'diabetes/envelhecimento favorecem demanda', 'endovascular, ultrassom vascular, pé diabético', 'Muito alta', 'Alta', 'Alta', 'B–C', 'Médio', 'Muito alto', 'Doppler/procedimentos elevam integração')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, program_years = EXCLUDED.program_years, total_training_years = EXCLUDED.total_training_years, prerequisite = EXCLUDED.prerequisite, surgical_profile = EXCLUDED.surgical_profile, weekly_hours_min = EXCLUDED.weekly_hours_min, weekly_hours_max = EXCLUDED.weekly_hours_max, quality_of_life_potential = EXCLUDED.quality_of_life_potential, telemedicine_potential = EXCLUDED.telemedicine_potential, work_settings = EXCLUDED.work_settings, market_absorption_proxy = EXCLUDED.market_absorption_proxy, future_demand_trend = EXCLUDED.future_demand_trend, ai_task_exposure = EXCLUDED.ai_task_exposure, geographic_market = EXCLUDED.geographic_market, market_note = EXCLUDED.market_note, career_paths = EXCLUDED.career_paths, private_practice_potential = EXCLUDED.private_practice_potential, hospital_potential = EXCLUDED.hospital_potential, research_teaching_potential = EXCLUDED.research_teaching_potential, clinic_class = EXCLUDED.clinic_class, capital_requirement = EXCLUDED.capital_requirement, private_revenue_potential = EXCLUDED.private_revenue_potential, economic_note = EXCLUDED.economic_note;

INSERT INTO public.clinic_cost_scenarios (class_code, structure, investment_min_brl, investment_max_brl, monthly_fixed_min_brl, monthly_fixed_max_brl) VALUES
  ('A', 'sala compartilhada / consultório básico', 25000, 80000, 8000, 20000),
  ('B', 'consultório próprio bem equipado', 80000, 200000, 15000, 35000),
  ('C', 'procedimentos/diagnóstico intermediário', 200000, 800000, 30000, 80000),
  ('D', 'centro diagnóstico/laboratório/equipamento pesado', 800000, NULL, 80000, NULL)
ON CONFLICT (class_code) DO UPDATE SET structure = EXCLUDED.structure, investment_min_brl = EXCLUDED.investment_min_brl, investment_max_brl = EXCLUDED.investment_max_brl, monthly_fixed_min_brl = EXCLUDED.monthly_fixed_min_brl, monthly_fixed_max_brl = EXCLUDED.monthly_fixed_max_brl;

INSERT INTO public.market_indicators (metric, geography, reference_year, value, unit, evidence_type, report_citation_refs) VALUES
  ('specialist_physicians', 'Brasil', 2024, 353287, 'pessoas', 'observado_no_relatorio', 'turn21view2;turn22view0'),
  ('specialist_share', 'Brasil', 2024, 59.1, '% dos médicos', 'observado_no_relatorio', 'turn21view2;turn22view0'),
  ('specialist_region_share', 'Sudeste', 2025, 55.4, '% dos especialistas', 'observado_no_relatorio', 'turn22view0'),
  ('specialist_region_share', 'Sul', 2025, 16.7, '% dos especialistas', 'observado_no_relatorio', 'turn22view0'),
  ('specialist_region_share', 'Nordeste', 2025, 14.5, '% dos especialistas', 'observado_no_relatorio', 'turn22view0'),
  ('specialist_region_share', 'Centro-Oeste', 2025, 7.5, '% dos especialistas', 'observado_no_relatorio', 'turn22view0'),
  ('specialist_region_share', 'Norte', 2025, 5.9, '% dos especialistas', 'observado_no_relatorio', 'turn22view0'),
  ('selected_specialists_federal_program', 'Bahia', 2025, 48, 'pessoas', 'observado_no_relatorio', 'turn22view1'),
  ('selected_specialists_federal_program', 'Brasil', 2025, 501, 'pessoas', 'observado_no_relatorio', 'turn22view1'),
  ('resident_monthly_stipend_gross', 'Brasil', 2026, 4106.09, 'BRL/mês', 'observado_no_relatorio', 'turn17search0'),
  ('resident_max_weekly_hours', 'Brasil', 2026, 60, 'horas/semana', 'observado_no_relatorio', 'turn16view1'),
  ('resident_max_on_call_hours', 'Brasil', 2026, 24, 'horas/semana', 'observado_no_relatorio', 'turn16view1'),
  ('annual_new_cancer_cases_estimate', 'Brasil', 2026, 781000, 'casos/ano', 'estimativa_fonte_no_relatorio', 'turn21view1'),
  ('enare_medical_vacancies', 'Brasil', 2026, 8287, 'vagas; ciclo 2026/27', 'observado_no_relatorio', 'turn10search24'),
  ('enare_medical_applications_approx', 'Brasil', 2026, 98000, 'inscrições; ciclo 2026/27', 'aproximado_no_relatorio', 'turn10search28')
ON CONFLICT (metric, geography, reference_year) DO UPDATE SET value = EXCLUDED.value, unit = EXCLUDED.unit, evidence_type = EXCLUDED.evidence_type, report_citation_refs = EXCLUDED.report_citation_refs;

INSERT INTO public.income_benchmarks
  (id, label, employer, geography, reference_year, monthly_gross_brl, weekly_hours, specialty_scope, source_url, note)
VALUES
  ('ebserh_2026_specialist_24h', 'Cargo de médico especialista', 'Ebserh', 'Brasil', 2026, 11464.35, 24,
   'Diversas especialidades do concurso nacional 01/2026',
   'https://conhecimento.fgv.br/sites/default/files/concursos/edital-no-02-area-medica-edital-retificado-1-30.01.2026.pdf',
   'Remuneração bruta anunciada para um vínculo de 24 horas semanais. Não representa renda média total, renda líquida nem garantia de vaga.')
ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label,
  employer = EXCLUDED.employer,
  geography = EXCLUDED.geography,
  reference_year = EXCLUDED.reference_year,
  monthly_gross_brl = EXCLUDED.monthly_gross_brl,
  weekly_hours = EXCLUDED.weekly_hours,
  specialty_scope = EXCLUDED.specialty_scope,
  source_url = EXCLUDED.source_url,
  note = EXCLUDED.note;

COMMIT;
